/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Connection.ConnectSQL;
import DAO.NhaCungCap_DAO;
import DAO.NhanVien_DAO;
import DAO.TaiKhoan_DAO;
import Entity.NhaCungCap;
import Entity.NhanVien;
import Entity.TaiKhoan;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinhh
 */
public class GUI_TaiKhoan extends javax.swing.JPanel {

    TaiKhoan_DAO dSTK = new TaiKhoan_DAO();
    private DefaultTableModel dataModel;
    NhanVien_DAO daoNV = new NhanVien_DAO();
    private ArrayList<NhanVien> dsNhanVien = daoNV.docTuBang();

    public GUI_TaiKhoan() {
        initComponents();
        dataModel = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Mã Nhân Viên", "Tên Nhân Viên", "Tên Tài Khoản", "Mật Khẩu", "Quyền Truy Cập"
                }
        );
        TableDSTaiKhoan.setModel(dataModel);
        ConnectSQL.getInstance().connect();
        getDataMaNhanVien();
        updateComboBox();
        updateAccountTableData();

    }

    private void updateComboBox() {
        NhanVien_DAO ds = new NhanVien_DAO();
        List<NhanVien> list = ds.docTuBang();
        cboMaNhanVien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(ItemEvent arg0) {
                if (arg0.getStateChange() == ItemEvent.SELECTED) {
                    String selectedMaNhanVien = cboMaNhanVien.getSelectedItem().toString();

                    NhanVien selectedNhanVien = null;
                    for (NhanVien nv : list) {
                        String maNV = nv.getMaNhanVien();
                        if (maNV.equals(selectedMaNhanVien)) { // Sử dụng .equals() để so sánh chuỗi
                            selectedNhanVien = nv;
                            System.out.println(selectedNhanVien);
                            break;
                        }
                    }
                    if (selectedNhanVien != null) {
                        txtTenNhanVien.setText(selectedNhanVien.getTenNhanVien());
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblQuanLyTaiKhoan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblMaNhanVien = new javax.swing.JLabel();
        lblTenNhanVien = new javax.swing.JLabel();
        lblTenTaiKhoan = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        lblQuyenTruyCap = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        txtTenTaiKhoan = new javax.swing.JTextField();
        cboQuyenTruyCap = new javax.swing.JComboBox<>();
        lblChucNang = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        cboMaNhanVien = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDSTaiKhoan = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblQuanLyTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuanLyTaiKhoan.setText("Quản Lý Tài Khoản");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(538, 538, 538)
                .addComponent(lblQuanLyTaiKhoan)
                .addContainerGap(593, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblQuanLyTaiKhoan)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaNhanVien.setText("Mã Nhân Viên");

        lblTenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTenNhanVien.setText("Tên Nhân Viên");

        lblTenTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTenTaiKhoan.setText("Tên Tài Khoản");

        lblMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMatKhau.setText("Mật Khẩu");

        lblQuyenTruyCap.setText("Quyền Truy Cập");

        cboQuyenTruyCap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên Bán Hàng", "Nhân Viên Quản Lý" }));

        lblChucNang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblChucNang.setText("Chức Năng");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_refesh.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_remove.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_change.png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblMaNhanVien)
                        .addComponent(lblTenTaiKhoan, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lblChucNang)
                    .addComponent(lblQuyenTruyCap, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenTaiKhoan)
                            .addComponent(cboMaNhanVien, 0, 265, Short.MAX_VALUE))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMatKhau)
                            .addComponent(lblTenNhanVien))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(txtMatKhau))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(45, 45, 45)
                                .addComponent(btnLamMoi)
                                .addGap(46, 46, 46)
                                .addComponent(btnXoa)
                                .addGap(42, 42, 42)
                                .addComponent(btnCapNhat))
                            .addComponent(cboQuyenTruyCap, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 548, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNhanVien)
                    .addComponent(lblTenNhanVien)
                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenTaiKhoan)
                    .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMatKhau))
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuyenTruyCap)
                    .addComponent(cboQuyenTruyCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChucNang)
                    .addComponent(btnThem)
                    .addComponent(btnLamMoi)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhat))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1596, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        TableDSTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Tên Tài Khoản", "Mât Khẩu", "Quyền Truy Cập"
            }
        ));
        TableDSTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDSTaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableDSTaiKhoan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        clearAccountTextFields();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void TableDSTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDSTaiKhoanMouseClicked
        int row = TableDSTaiKhoan.getSelectedRow();

        if (row >= 0) {
            String maNhanVienStr = getValueAt(row, 0);
            String tenNhanVienStr = getValueAt(row, 1);
            String tenTaiKhoanStr = getValueAt(row, 2);
            String matKhauStr = getValueAt(row, 3);
            String quyenTruyCapStr = getValueAt(row, 4);

            cboMaNhanVien.setSelectedItem(maNhanVienStr);
            txtTenNhanVien.setText(tenNhanVienStr);
            txtTenTaiKhoan.setText(tenTaiKhoanStr);
            txtMatKhau.setText(matKhauStr);
            cboQuyenTruyCap.setSelectedItem(quyenTruyCapStr);
        }
    }//GEN-LAST:event_TableDSTaiKhoanMouseClicked
    private String getValueAt(int row, int column) {
        Object value = TableDSTaiKhoan.getValueAt(row, column);
        if (value != null) {
            return value.toString();
        }
        return ""; // Trả về chuỗi rỗng nếu giá trị là null
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            TaiKhoan account = revertAccountFormTextFile();
            if (dSTK.create(account)) {
                Object[] rowData = {
                    account.getMaNhanVien(),
                    account.getTenNhanVien(),
                    account.getTenTaiKhoan(),
                    account.getMatKhau(),
                    account.getQuyenTruyCap(),};
                dataModel.addRow(rowData);
            }
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = TableDSTaiKhoan.getSelectedRow();
        if (row >= 0) {
            String supplierCode = TableDSTaiKhoan.getValueAt(row, 0).toString();

            if (dSTK.delete(supplierCode)) {
                dataModel.removeRow(row);

            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        int row = TableDSTaiKhoan.getSelectedRow();
        if (row >= 0) {
            TaiKhoan acc = revertAccountFormTextFile();
            if (dSTK.update(acc)) {
                TableDSTaiKhoan.setValueAt(acc.getMaNhanVien(), row, 0);
                TableDSTaiKhoan.setValueAt(acc.getTenNhanVien(), row, 1);
                TableDSTaiKhoan.setValueAt(acc.getTenTaiKhoan(), row, 2);
                TableDSTaiKhoan.setValueAt(acc.getMatKhau(), row, 3);
                TableDSTaiKhoan.setValueAt(acc.getQuyenTruyCap(), row, 4);
            }
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed
    private void clearAccountTextFields() {
        txtTenNhanVien.setText("");
        cboMaNhanVien.setSelectedIndex(0);
        txtTenTaiKhoan.setText("");
        txtMatKhau.setText("");
        cboQuyenTruyCap.setSelectedIndex(0);

       
    }

    private void getDataMaNhanVien() {
        for (int i = 0; i < dsNhanVien.size(); i++) {
            cboMaNhanVien.addItem(String.valueOf(dsNhanVien.get(i).getMaNhanVien()));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDSTaiKhoan;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboMaNhanVien;
    private javax.swing.JComboBox<String> cboQuyenTruyCap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChucNang;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblQuanLyTaiKhoan;
    private javax.swing.JLabel lblQuyenTruyCap;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lblTenTaiKhoan;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtTenTaiKhoan;
    // End of variables declaration//GEN-END:variables

    private void updateAccountTableData() {

        TaiKhoan_DAO account_DAO = new TaiKhoan_DAO();
        List<TaiKhoan> accounts = account_DAO.docTuBang();

        // Clear the existing data in the table (if needed).
        dataModel.setRowCount(0);

        for (TaiKhoan account : accounts) {
            String[] rowData = {
                account.getMaNhanVien(),
                account.getTenNhanVien(),
                account.getTenTaiKhoan(),
                account.getMatKhau(),
                account.getQuyenTruyCap(),};
            dataModel.addRow(rowData);
        }
        TableDSTaiKhoan.setModel(dataModel);
    }

    private TaiKhoan revertAccountFormTextFile() {
        String maNhanVien = cboMaNhanVien.getSelectedItem().toString();
        String tenNhanVien = txtTenNhanVien.getText();
        String tenTaiKhoan = txtTenTaiKhoan.getText();
        String matKhau = txtMatKhau.getText();
        String quyenTruyCap = cboQuyenTruyCap.getSelectedItem().toString();
        return new TaiKhoan(maNhanVien, tenNhanVien,tenTaiKhoan, matKhau, quyenTruyCap );
    }

}
