
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Connection.ConnectSQL;
import DAO.NhanVien_DAO;
import Entity.NhanVien;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinhh
 */
public class GUI_QuanLyNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form NhanVien
     */
    String filename = null;
    byte[] person_image = null;
    NhanVien_DAO nhanVienDAO = new NhanVien_DAO();
    private DefaultTableModel dataModel;

    public GUI_QuanLyNhanVien() {
        initComponents();
        dataModel = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Mã Nhân Viên", "Tên Nhân Viên", "Giới Tính", "Ngày Sinh", "Số Điện Thoại", "Địa Chỉ", "Chức Vụ", "Hình Ảnh"
                }
        );
        TableDSNhanVien.setModel(dataModel);
        ConnectSQL.getInstance().connect();
        updateEmployeeTableData();
    }

    private void updateEmployeeTableData() {
        NhanVien_DAO employeeDAO = new NhanVien_DAO();
        List<NhanVien> employees = employeeDAO.docTuBang();

        dataModel.setRowCount(0);

        for (NhanVien employee : employees) {
            String[] rowData = {
                employee.getMaNhanVien(),
                employee.getTenNhanVien(),
                employee.getGioiTinh(),
                employee.getNgaySinh().toString(),
                String.valueOf(employee.getSDT()),
                employee.getDiaChi(),
                employee.getChucVu()
            };
            dataModel.addRow(rowData);
        }
        TableDSNhanVien.setModel(dataModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDSNhanVien = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dateNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnThemNhanVien = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblAnh = new javax.swing.JLabel();
        btnChonAnh = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cboChucVu = new javax.swing.JComboBox<>();
        cboGioiTinh = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        TableDSNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Giới Tính", "Ngày Sinh", "Số Điện Thoại", "Địa Chỉ", "Chức Vụ", "Hình Ảnh"
            }
        ));
        TableDSNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDSNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableDSNhanVien);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1197, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 409, 1200, 343));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(546, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(447, 447, 447))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 9, 1170, 40));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.setForeground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Mã Nhân Viên");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 48, 102, -1));
        jPanel3.add(txtTenNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 45, 220, -1));

        jLabel3.setText("Tên Nhân Viên");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 102, -1));
        jPanel3.add(txtMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 45, 214, -1));

        jLabel4.setText("Số Điện Thoại");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 177, 102, -1));

        jLabel5.setText("Giới Tính");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 104, 102, -1));
        jPanel3.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 174, 220, -1));

        jLabel6.setText("Địa Chỉ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 102, -1));
        jPanel3.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 217, -1));

        jLabel7.setText("Ngày Sinh");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 102, -1));
        jPanel3.add(dateNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 101, 220, -1));

        jLabel8.setText("Chức Vụ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 243, -1, -1));

        jLabel9.setText("Chức Năng");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 309, -1, -1));

        btnThemNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_add.png"))); // NOI18N
        btnThemNhanVien.setText("Thêm");
        btnThemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhanVienActionPerformed(evt);
            }
        });
        jPanel3.add(btnThemNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, 30));

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_refesh.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        jPanel3.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 120, 30));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_change.png"))); // NOI18N
        btnSua.setText("Cập Nhật");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel3.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, 30));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_remove.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel3.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 90, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 210, 230));

        btnChonAnh.setText("Chọn Ảnh");
        btnChonAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChonAnhMouseClicked(evt);
            }
        });
        jPanel3.add(btnChonAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 290, -1, -1));

        jLabel10.setText("Hình Ảnh Nhân Viên");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, -1));

        cboChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên Bán Hàng", "Nhân Viên Quản Lý" }));
        jPanel3.add(cboChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 217, -1));

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jPanel3.add(cboGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 210, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 1190, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = TableDSNhanVien.getSelectedRow();
        if (row >= 0) {
            NhanVien employee = revertNVFormTextFile();
            if (employee != null) {
                if (nhanVienDAO.update(employee)) {
                    TableDSNhanVien.setValueAt(employee.getMaNhanVien(), row, 0);
                    TableDSNhanVien.setValueAt(employee.getTenNhanVien(), row, 1);
                    TableDSNhanVien.setValueAt(employee.getGioiTinh(), row, 2);
                    TableDSNhanVien.setValueAt(employee.getNgaySinh(), row, 3);
                    TableDSNhanVien.setValueAt(employee.getSDT(), row, 4);
                    TableDSNhanVien.setValueAt(employee.getDiaChi(), row, 5);
                    TableDSNhanVien.setValueAt(employee.getChucVu(), row, 6);

                }
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = TableDSNhanVien.getSelectedRow();
        if (row >= 0) {
            String maNhanVien = TableDSNhanVien.getValueAt(row, 0).toString();

            if (nhanVienDAO.delete(maNhanVien)) {
                dataModel.removeRow(row);
            }
        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnChonAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChonAnhMouseClicked
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lblAnh.getWidth(), lblAnh.getHeight(), Image.SCALE_SMOOTH));
        lblAnh.setIcon(imageIcon);
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
            }
            person_image = bos.toByteArray();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnChonAnhMouseClicked

    private void btnThemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhanVienActionPerformed
        try {
            NhanVien employee = revertNVFormTextFile();
            if (NhanVien_DAO.create(employee)) {
                Object[] rowData = {
                    employee.getMaNhanVien(),
                    employee.getTenNhanVien(),
                    employee.getGioiTinh(),
                    employee.getNgaySinh().toString(),
                    employee.getSDT(),
                    employee.getDiaChi(),
                    employee.getChucVu(),
                    employee.getHinhAnh()
                };
                dataModel.addRow(rowData);
            }
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemNhanVienActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        clearEmployeeTextFields();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void TableDSNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDSNhanVienMouseClicked

        int row = TableDSNhanVien.getSelectedRow();
        if (row >= 0) {
            txtMaNhanVien.setText(TableDSNhanVien.getValueAt(row, 0).toString());
            txtTenNhanVien.setText(TableDSNhanVien.getValueAt(row, 1).toString());
            // Lấy giới tính từ bảng và đặt giá trị cho comboBox gioiTinh
            String gioiTinhStr = TableDSNhanVien.getValueAt(row, 2).toString();
            if (gioiTinhStr.equals("Nam")) {
                cboGioiTinh.setSelectedItem("Nam");
            } else {
                cboGioiTinh.setSelectedItem("Nữ");
            }

            String ngaySinhStr = TableDSNhanVien.getValueAt(row, 3).toString();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            try {
                Date ngaySinh = sdf.parse(ngaySinhStr);
                dateNgaySinh.setDate(ngaySinh);
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
            txtSDT.setText(TableDSNhanVien.getValueAt(row, 4).toString());
            txtDiaChi.setText(TableDSNhanVien.getValueAt(row, 5).toString());
            String chucVuStr = TableDSNhanVien.getValueAt(row, 6).toString();
            cboChucVu.setSelectedItem(chucVuStr);

            // Hiển thị hình ảnh khi nhấp chuột vào hàng trong bảng
            byte[] img = nhanVienDAO.docTuBang().get(row).getHinhAnh();
            if (img != null) {
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblAnh.getWidth(), lblAnh.getHeight(), Image.SCALE_SMOOTH));
                lblAnh.setIcon(imageIcon);
            } else {
                // Nếu hình ảnh không tồn tại, bạn có thể đặt JLabel lblAnh về null hoặc hiển thị một hình mặc định.
                lblAnh.setIcon(null); // Hoặc hiển thị một hình ảnh mặc định
            }

        }

    }//GEN-LAST:event_TableDSNhanVienMouseClicked
    private NhanVien revertNVFormTextFile() {
        String maNhanVien = txtMaNhanVien.getText();
        if (!maNhanVien.matches("^NV\\d{3}$")) {
            JOptionPane.showMessageDialog(null, "Mã nhân viên không hợp lệ", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        String tenNhanVien = txtTenNhanVien.getText();
        if (tenNhanVien.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tên nhân viên không được để trống", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        String gioiTinhStr = cboGioiTinh.getSelectedItem().toString();
        String gioiTinh = cboGioiTinh.getSelectedItem().toString();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = dateNgaySinh.getDate();
        String ngaySinh = sdf.format(date);
        String sdt = txtSDT.getText().toString();
        if (!sdt.matches("^[0-9]{10}$")) {
            JOptionPane.showMessageDialog(null, "Số điện thoại phải có 10 số", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        String diaChi = txtDiaChi.getText();
        if (diaChi.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Địa chỉ không được để trống", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        String chucVu = cboChucVu.getSelectedItem().toString();

        ImageIcon imageIcon = (ImageIcon) lblAnh.getIcon();
        byte[] imageBytes = null;

        if (imageIcon != null) {
            // Chuyển đổi ImageIcon thành mảng byte
            BufferedImage bufferedImage = new BufferedImage(imageIcon.getIconWidth(), imageIcon.getIconHeight(), BufferedImage.TYPE_INT_RGB);
            Graphics2D g2d = bufferedImage.createGraphics();
            imageIcon.paintIcon(lblAnh, g2d, 0, 0);
            g2d.dispose();

            try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
                ImageIO.write(bufferedImage, "jpg", baos);
                imageBytes = baos.toByteArray();
            } catch (IOException e) {
                e.printStackTrace();
            }

            // Tiếp theo, bạn có thể lưu mảng byte 'imageBytes' vào đối tượng NhanVien
        }

        return new NhanVien(maNhanVien, tenNhanVien, gioiTinh, ngaySinh, sdt, diaChi, chucVu, imageBytes);
    }

    private void clearEmployeeTextFields() {
        txtMaNhanVien.setText("");
        txtTenNhanVien.setText("");
        cboChucVu.setSelectedIndex(0);
        cboGioiTinh.setSelectedIndex(0);
        txtSDT.setText("");
        txtDiaChi.setText("");
        dateNgaySinh.setDate(null);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDSNhanVien;
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemNhanVien;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboChucVu;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private com.toedter.calendar.JDateChooser dateNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNhanVien;
    // End of variables declaration//GEN-END:variables

}
